"use client";

import { createContext, useContext, useState, ReactNode } from "react";

const translations: Record<string, Record<string, string>> = {
  en: {
    home: "Home",
    timeline: "Timeline",
    recipes: "Recipes",
    voices: "Voices",
    wisdom: "Wisdom",
    gallery: "Gallery",
    bedtime: "Bedtime",
    card: "Card",
    loveLetter: "Love Letter",
    gratitude: "Gratitude",
    quiz: "Quiz",
    familyTree: "Family Tree",
    promises: "Promises",
    celebration: "Celebration",
    subtitle: "Your Mother's Story, Beautifully Preserved",
    cta: "Create Her Story",
    addMemory: "Add Memory",
    addRecipe: "Add Recipe",
    addWisdom: "Add Wisdom",
    record: "Record a Memory",
    generateCard: "Generate Card",
    cookAlong: "Cook Along",
    nightMode: "Night Mode",
    date: "Date",
    title: "Title",
    description: "Description",
    save: "Save",
    cancel: "Cancel",
    uploadPhoto: "Upload Photo",
    ingredients: "Ingredients",
    instructions: "Instructions",
    photo: "Photo",
    momName: "Mom's Name",
    message: "Your Message",
    download: "Download",
    playing: "Playing...",
    recording: "Recording...",
    noMemories: "No memories yet. Add your first!",
    noRecipes: "No recipes yet. Add one!",
    noVoices: "No recordings yet. Start recording!",
    noWisdom: "No wisdom yet. Share some advice!",
    noPhotos: "No photos yet. Upload one!",
    step: "Step",
    of: "of",
    heroTagline: "Every mother has a story worth telling",
    loveLetterTitle: "Love Letter to Mom",
    loveLetterDesc: "Pour your heart out in a beautiful letter",
    writeLetter: "Write Your Letter",
    chooseTemplate: "Choose a Template",
    revealLetter: "Reveal Letter",
    printLetter: "Print Letter",
    templateMother: "For My Mother",
    templateThankYou: "Thank You Mom",
    templateGrandma: "To My Grandma",
    templateFromAfar: "A Letter From Afar",
    gratitudeTitle: "Gratitude Journal",
    gratitudeDesc: "Daily gratitude for the woman who gave you everything",
    todayGrateful: "Today I'm Grateful For...",
    addGratitude: "Add Gratitude",
    streak: "Day Streak",
    monthlyReflection: "Monthly Reflection",
    quizTitle: "How Well Do You Know Your Mom?",
    quizDesc: "Test your knowledge about the most important woman in your life",
    startQuiz: "Start Quiz",
    submitQuiz: "See Results",
    nextQuestion: "Next",
    yourAnswer: "Your Answer",
    momsAnswer: "Mom's Answer",
    score: "Your Score",
    customQuestion: "Add Custom Question",
    familyTreeTitle: "Family Tree",
    familyTreeDesc: "Map the roots of your family's love",
    addMember: "Add Family Member",
    name: "Name",
    relation: "Relation",
    birthYear: "Birth Year",
    parent: "Parent",
    promisesTitle: "Promises to Mom",
    promisesDesc: "Make and keep promises to the woman who deserves everything",
    addPromise: "Add Promise",
    keptPromises: "Kept",
    totalPromises: "Total",
    markKept: "Mark as Kept",
    celebrationTitle: "Countdown & Celebration",
    celebrationDesc: "Never miss a special day for Mom",
    mothersDay: "Mother's Day",
    birthday: "Birthday",
    configure: "Configure",
    daysLeft: "Days Left",
    hoursLeft: "Hours",
    minutesLeft: "Minutes",
    secondsLeft: "Seconds",
    happyMothersDay: "Happy Mother's Day!",
    happyBirthday: "Happy Birthday!",
    reasonsILoveYou: "Reasons I Love You, Mom",
    features: "Features",
    testimonialsTitle: "What People Say",
    cardTemplates: "Card Templates",
    templateMothersDay: "Happy Mother's Day",
    templateILoveYou: "I Love You",
    templateHero: "You're My Hero",
    fontChoice: "Font Style",
    colorTheme: "Color Theme",
    preset: "Preset",
    custom: "Custom",
  },
  bn: {
    home: "হোম",
    timeline: "টাইমলাইন",
    recipes: "রেসিপি",
    voices: "কণ্ঠ",
    wisdom: "প্রজ্ঞা",
    gallery: "গ্যালারি",
    bedtime: "গল্পের সময়",
    card: "কার্ড",
    loveLetter: "প্রেমের চিঠি",
    gratitude: "কৃতজ্ঞতা",
    quiz: "কুইজ",
    familyTree: "পারিবারিক বৃক্ষ",
    promises: "প্রতিশ্রুতি",
    celebration: "উদযাপন",
    subtitle: "আপনার মায়ের গল্প, সুন্দরভাবে সংরক্ষিত",
    cta: "তার গল্প তৈরি করুন",
    addMemory: "স্মৃতি যোগ করুন",
    addRecipe: "রেসিপি যোগ করুন",
    addWisdom: "প্রজ্ঞা যোগ করুন",
    record: "স্মৃতি রেকর্ড করুন",
    generateCard: "কার্ড তৈরি করুন",
    cookAlong: "রান্না করুন",
    nightMode: "রাত্রি মোড",
    date: "তারিখ",
    title: "শিরোনাম",
    description: "বিবরণ",
    save: "সংরক্ষণ",
    cancel: "বাতিল",
    uploadPhoto: "ছবি আপলোড করুন",
    ingredients: "উপকরণ",
    instructions: "নির্দেশনা",
    photo: "ছবি",
    momName: "মায়ের নাম",
    message: "আপনার বার্তা",
    download: "ডাউনলোড",
    playing: "চলছে...",
    recording: "রেকর্ড হচ্ছে...",
    noMemories: "এখনো কোনো স্মৃতি নেই। প্রথমটি যোগ করুন!",
    noRecipes: "এখনো কোনো রেসিপি নেই। একটি যোগ করুন!",
    noVoices: "এখনো কোনো রেকর্ডিং নেই। শুরু করুন!",
    noWisdom: "এখনো কোনো প্রজ্ঞা নেই। কিছু উপদেশ শেয়ার করুন!",
    noPhotos: "এখনো কোনো ছবি নেই। একটি আপলোড করুন!",
    step: "ধাপ",
    of: "এর মধ্যে",
    heroTagline: "প্রতিটি মায়ের একটি গল্প আছে যা বলা উচিত",
    loveLetterTitle: "মাকে প্রেমের চিঠি",
    loveLetterDesc: "সুন্দর চিঠিতে মনের কথা বলুন",
    writeLetter: "আপনার চিঠি লিখুন",
    chooseTemplate: "টেমপ্লেট বেছে নিন",
    revealLetter: "চিঠি দেখুন",
    printLetter: "চিঠি প্রিন্ট করুন",
    templateMother: "আমার মায়ের জন্য",
    templateThankYou: "ধন্যবাদ মা",
    templateGrandma: "দাদীমাকে",
    templateFromAfar: "দূর থেকে একটি চিঠি",
    gratitudeTitle: "কৃতজ্ঞতা জার্নাল",
    gratitudeDesc: "প্রতিদিন সেই নারীর প্রতি কৃতজ্ঞতা যিনি আপনাকে সব দিয়েছেন",
    todayGrateful: "আজ আমি কৃতজ্ঞ...",
    addGratitude: "কৃতজ্ঞতা যোগ করুন",
    streak: "দিনের স্ট্রিক",
    monthlyReflection: "মাসিক প্রতিফলন",
    quizTitle: "আপনি কতটা ভালো চেনেন আপনার মাকে?",
    quizDesc: "আপনার জীবনের সবচেয়ে গুরুত্বপূর্ণ নারী সম্পর্কে আপনার জ্ঞান পরীক্ষা করুন",
    startQuiz: "কুইজ শুরু করুন",
    submitQuiz: "ফলাফল দেখুন",
    nextQuestion: "পরবর্তী",
    yourAnswer: "আপনার উত্তর",
    momsAnswer: "মায়ের উত্তর",
    score: "আপনার স্কোর",
    customQuestion: "কাস্টম প্রশ্ন যোগ করুন",
    familyTreeTitle: "পারিবারিক বৃক্ষ",
    familyTreeDesc: "আপনার পরিবারের ভালোবাসার শিকড় ম্যাপ করুন",
    addMember: "সদস্য যোগ করুন",
    name: "নাম",
    relation: "সম্পর্ক",
    birthYear: "জন্ম সাল",
    parent: "পিতামাতা",
    promisesTitle: "মায়ের কাছে প্রতিশ্রুতি",
    promisesDesc: "সেই নারীকে প্রতিশ্রুতি দিন যিনি সব প্রাপ্য",
    addPromise: "প্রতিশ্রুতি যোগ করুন",
    keptPromises: "রাখা হয়েছে",
    totalPromises: "মোট",
    markKept: "রাখা হয়েছে চিহ্নিত করুন",
    celebrationTitle: "কাউন্টডাউন ও উদযাপন",
    celebrationDesc: "মায়ের জন্য বিশেষ দিন কখনো মিস করবেন না",
    mothersDay: "মাতৃ দিবস",
    birthday: "জন্মদিন",
    configure: "কনফিগার করুন",
    daysLeft: "দিন বাকি",
    hoursLeft: "ঘণ্টা",
    minutesLeft: "মিনিট",
    secondsLeft: "সেকেন্ড",
    happyMothersDay: "শুভ মাতৃ দিবস!",
    happyBirthday: "শুভ জন্মদিন!",
    reasonsILoveYou: "আমি কেন তোমাকে ভালোবাসি, মা",
    features: "বৈশিষ্ট্য",
    testimonialsTitle: "মানুষ কী বলে",
    cardTemplates: "কার্ড টেমপ্লেট",
    templateMothersDay: "শুভ মাতৃ দিবস",
    templateILoveYou: "আমি তোমাকে ভালোবাসি",
    templateHero: "তুমিই আমার হিরো",
    fontChoice: "ফন্ট স্টাইল",
    colorTheme: "রঙের থিম",
    preset: "প্রিসেট",
    custom: "কাস্টম",
  },
};

type Lang = "en" | "bn";
const LanguageContext = createContext<{ lang: Lang; t: (key: string) => string; toggle: () => void }>({
  lang: "en",
  t: (k) => translations.en[k] || k,
  toggle: () => {},
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");
  const toggle = () => setLang((l) => (l === "en" ? "bn" : "en"));
  const t = (key: string) => translations[lang][key] || translations.en[key] || key;
  return <LanguageContext.Provider value={{ lang, t, toggle }}>{children}</LanguageContext.Provider>;
}

export const useLang = () => useContext(LanguageContext);
