"use client";

import { createContext, useContext, useState, ReactNode } from "react";

const translations: Record<string, Record<string, string>> = {
  en: {
    home: "Home",
    timeline: "Timeline",
    recipes: "Recipes",
    voices: "Voices",
    wisdom: "Wisdom",
    gallery: "Gallery",
    bedtime: "Bedtime",
    card: "Card",
    loveLetter: "Love Letter",
    gratitude: "Gratitude",
    quiz: "Quiz",
    familyTree: "Family Tree",
    promises: "Promises",
    celebration: "Celebration",
    collage: "Collage",
    coupons: "Coupons",
    bucketList: "Bucket List",
    giftBox: "Gift Box",
    memoryJar: "Memory Jar",
    photoBooth: "Photo Booth",
    subtitle: "Your Mother's Story, Beautifully Preserved",
    cta: "Create Her Story",
    addMemory: "Add Memory",
    addRecipe: "Add Recipe",
    addWisdom: "Add Wisdom",
    record: "Record a Memory",
    generateCard: "Generate Card",
    cookAlong: "Cook Along",
    nightMode: "Night Mode",
    date: "Date",
    title: "Title",
    description: "Description",
    save: "Save",
    cancel: "Cancel",
    uploadPhoto: "Upload Photo",
    ingredients: "Ingredients",
    instructions: "Instructions",
    photo: "Photo",
    momName: "Mom's Name",
    message: "Your Message",
    download: "Download",
    playing: "Playing...",
    recording: "Recording...",
    noMemories: "No memories yet. Add your first!",
    noRecipes: "No recipes yet. Add one!",
    noVoices: "No recordings yet. Start recording!",
    noWisdom: "No wisdom yet. Share some advice!",
    noPhotos: "No photos yet. Upload one!",
    step: "Step",
    of: "of",
    heroTagline: "Every mother has a story worth telling",
    loveLetterTitle: "Love Letter to Mom",
    loveLetterDesc: "Pour your heart out in a beautiful letter",
    writeLetter: "Write Your Letter",
    chooseTemplate: "Choose a Template",
    revealLetter: "Reveal Letter",
    printLetter: "Print Letter",
    templateMother: "For My Mother",
    templateThankYou: "Thank You Mom",
    templateGrandma: "To My Grandma",
    templateFromAfar: "A Letter From Afar",
    gratitudeTitle: "Gratitude Journal",
    gratitudeDesc: "Daily gratitude for the woman who gave you everything",
    todayGrateful: "Today I'm Grateful For...",
    addGratitude: "Add Gratitude",
    streak: "Day Streak",
    monthlyReflection: "Monthly Reflection",
    quizTitle: "How Well Do You Know Your Mom?",
    quizDesc: "Test your knowledge about the most important woman in your life",
    startQuiz: "Start Quiz",
    submitQuiz: "See Results",
    nextQuestion: "Next",
    yourAnswer: "Your Answer",
    momsAnswer: "Mom's Answer",
    score: "Your Score",
    customQuestion: "Add Custom Question",
    familyTreeTitle: "Family Tree",
    familyTreeDesc: "Map the roots of your family's love",
    addMember: "Add Family Member",
    name: "Name",
    relation: "Relation",
    birthYear: "Birth Year",
    parent: "Parent",
    promisesTitle: "Promises to Mom",
    promisesDesc: "Make and keep promises to the woman who deserves everything",
    addPromise: "Add Promise",
    keptPromises: "Kept",
    totalPromises: "Total",
    markKept: "Mark as Kept",
    celebrationTitle: "Countdown & Celebration",
    celebrationDesc: "Never miss a special day for Mom",
    mothersDay: "Mother's Day",
    birthday: "Birthday",
    configure: "Configure",
    daysLeft: "Days Left",
    hoursLeft: "Hours",
    minutesLeft: "Minutes",
    secondsLeft: "Seconds",
    happyMothersDay: "Happy Mother's Day!",
    happyBirthday: "Happy Birthday!",
    reasonsILoveYou: "Reasons I Love You, Mom",
    features: "Features",
    testimonialsTitle: "What People Say",
    cardTemplates: "Card Templates",
    templateMothersDay: "Happy Mother's Day",
    templateILoveYou: "I Love You",
    templateHero: "You're My Hero",
    fontChoice: "Font Style",
    colorTheme: "Color Theme",
    preset: "Preset",
    custom: "Custom",
    // Collage
    collageTitle: "Photo Collage Maker",
    collageDesc: "Create beautiful photo collages for Mom",
    chooseLayout: "Choose Layout",
    addPhotos: "Add Photos",
    collageTitleLabel: "Collage Title",
    downloadCollage: "Download Collage",
    shareCollage: "Share Collage",
    layoutGrid: "Grid",
    layoutHeart: "Heart",
    layoutCircle: "Circle",
    layoutStrip: "Photo Strip",
    // Coupons
    couponTitle: "Mom Coupons",
    couponDesc: "Create redeemable love coupons for Mom",
    addCoupon: "Add Coupon",
    redeem: "Redeem",
    redeemed: "Redeemed",
    printCoupons: "Print Coupon Book",
    customCoupon: "Custom Coupon",
    // Bucket List
    bucketListTitle: "Mom & Me Bucket List",
    bucketListDesc: "Things to do together before the end of time",
    addItem: "Add Item",
    completed: "Completed",
    remaining: "Remaining",
    adventures: "Adventures",
    food: "Food",
    qualityTime: "Quality Time",
    learning: "Learning",
    // Gift Box
    giftBoxTitle: "Digital Gift Box",
    giftBoxDesc: "Create a surprise gift box for Mom",
    openGift: "Open Gift Box",
    addGift: "Add Gift",
    textGift: "Love Message",
    photoGift: "Photo Gift",
    couponGift: "Coupon Gift",
    chooseTheme: "Choose Box Theme",
    // Memory Jar
    jarTitle: "Memory Jar",
    jarDesc: "Fill a jar with love notes and memories",
    addNote: "Add Note",
    drawNote: "Draw a Note",
    shakeJar: "Shake Jar",
    noteText: "Your loving thought...",
    // Photo Booth
    boothTitle: "Photo Booth",
    boothDesc: "Take fun photos with Mom",
    startCamera: "Start Camera",
    capture: "Capture!",
    filterNone: "Normal",
    filterWarm: "Warm",
    filterVintage: "Vintage",
    filterBW: "B&W",
    filterVibrant: "Vibrant",
    frameBestMom: "Best Mom",
    frameHearts: "Hearts",
    frameFlowers: "Flowers",
    saveToGallery: "Save to Gallery",
    downloadPhoto: "Download",
    // Share
    shareTitle: "Share with Mom",
    share: "Share",
    shareWhatsApp: "WhatsApp",
    shareFacebook: "Facebook",
    shareTwitter: "Twitter/X",
    shareCopyLink: "Copy Link",
    shareDownload: "Download Image",
    shareText: "I made this for my mom! ❤️ #LoveYouMom #BuiltWithTRAE",
    // General
    builtWithTRAE: "Built with TRAE IDE",
  },
  bn: {
    home: "হোম",
    timeline: "টাইমলাইন",
    recipes: "রেসিপি",
    voices: "কণ্ঠ",
    wisdom: "প্রজ্ঞা",
    gallery: "গ্যালারি",
    bedtime: "গল্পের সময়",
    card: "কার্ড",
    loveLetter: "প্রেমের চিঠি",
    gratitude: "কৃতজ্ঞতা",
    quiz: "কুইজ",
    familyTree: "পারিবারিক বৃক্ষ",
    promises: "প্রতিশ্রুতি",
    celebration: "উদযাপন",
    collage: "কোলাজ",
    coupons: "কুপন",
    bucketList: "বাকেট লিস্ট",
    giftBox: "গিফট বক্স",
    memoryJar: "মেমোরি জার",
    photoBooth: "ফটো বুথ",
    subtitle: "আপনার মায়ের গল্প, সুন্দরভাবে সংরক্ষিত",
    cta: "তার গল্প তৈরি করুন",
    addMemory: "স্মৃতি যোগ করুন",
    addRecipe: "রেসিপি যোগ করুন",
    addWisdom: "প্রজ্ঞা যোগ করুন",
    record: "স্মৃতি রেকর্ড করুন",
    generateCard: "কার্ড তৈরি করুন",
    cookAlong: "রান্না করুন",
    nightMode: "রাত্রি মোড",
    date: "তারিখ",
    title: "শিরোনাম",
    description: "বিবরণ",
    save: "সংরক্ষণ",
    cancel: "বাতিল",
    uploadPhoto: "ছবি আপলোড করুন",
    ingredients: "উপকরণ",
    instructions: "নির্দেশনা",
    photo: "ছবি",
    momName: "মায়ের নাম",
    message: "আপনার বার্তা",
    download: "ডাউনলোড",
    playing: "চলছে...",
    recording: "রেকর্ড হচ্ছে...",
    noMemories: "এখনো কোনো স্মৃতি নেই। প্রথমটি যোগ করুন!",
    noRecipes: "এখনো কোনো রেসিপি নেই। একটি যোগ করুন!",
    noVoices: "এখনো কোনো রেকর্ডিং নেই। শুরু করুন!",
    noWisdom: "এখনো কোনো প্রজ্ঞা নেই। কিছু উপদেশ শেয়ার করুন!",
    noPhotos: "এখনো কোনো ছবি নেই। একটি আপলোড করুন!",
    step: "ধাপ",
    of: "এর মধ্যে",
    heroTagline: "প্রতিটি মায়ের একটি গল্প আছে যা বলা উচিত",
    loveLetterTitle: "মাকে প্রেমের চিঠি",
    loveLetterDesc: "সুন্দর চিঠিতে মনের কথা বলুন",
    writeLetter: "আপনার চিঠি লিখুন",
    chooseTemplate: "টেমপ্লেট বেছে নিন",
    revealLetter: "চিঠি দেখুন",
    printLetter: "চিঠি প্রিন্ট করুন",
    templateMother: "আমার মায়ের জন্য",
    templateThankYou: "ধন্যবাদ মা",
    templateGrandma: "দাদীমাকে",
    templateFromAfar: "দূর থেকে একটি চিঠি",
    gratitudeTitle: "কৃতজ্ঞতা জার্নাল",
    gratitudeDesc: "প্রতিদিন সেই নারীর প্রতি কৃতজ্ঞতা যিনি আপনাকে সব দিয়েছেন",
    todayGrateful: "আজ আমি কৃতজ্ঞ...",
    addGratitude: "কৃতজ্ঞতা যোগ করুন",
    streak: "দিনের স্ট্রিক",
    monthlyReflection: "মাসিক প্রতিফলন",
    quizTitle: "আপনি কতটা ভালো চেনেন আপনার মাকে?",
    quizDesc: "আপনার জীবনের সবচেয়ে গুরুত্বপূর্ণ নারী সম্পর্কে আপনার জ্ঞান পরীক্ষা করুন",
    startQuiz: "কুইজ শুরু করুন",
    submitQuiz: "ফলাফল দেখুন",
    nextQuestion: "পরবর্তী",
    yourAnswer: "আপনার উত্তর",
    momsAnswer: "মায়ের উত্তর",
    score: "আপনার স্কোর",
    customQuestion: "কাস্টম প্রশ্ন যোগ করুন",
    familyTreeTitle: "পারিবারিক বৃক্ষ",
    familyTreeDesc: "আপনার পরিবারের ভালোবাসার শিকড় ম্যাপ করুন",
    addMember: "সদস্য যোগ করুন",
    name: "নাম",
    relation: "সম্পর্ক",
    birthYear: "জন্ম সাল",
    parent: "পিতামাতা",
    promisesTitle: "মায়ের কাছে প্রতিশ্রুতি",
    promisesDesc: "সেই নারীকে প্রতিশ্রুতি দিন যিনি সব প্রাপ্য",
    addPromise: "প্রতিশ্রুতি যোগ করুন",
    keptPromises: "রাখা হয়েছে",
    totalPromises: "মোট",
    markKept: "রাখা হয়েছে চিহ্নিত করুন",
    celebrationTitle: "কাউন্টডাউন ও উদযাপন",
    celebrationDesc: "মায়ের জন্য বিশেষ দিন কখনো মিস করবেন না",
    mothersDay: "মাতৃ দিবস",
    birthday: "জন্মদিন",
    configure: "কনফিগার করুন",
    daysLeft: "দিন বাকি",
    hoursLeft: "ঘণ্টা",
    minutesLeft: "মিনিট",
    secondsLeft: "সেকেন্ড",
    happyMothersDay: "শুভ মাতৃ দিবস!",
    happyBirthday: "শুভ জন্মদিন!",
    reasonsILoveYou: "আমি কেন তোমাকে ভালোবাসি, মা",
    features: "বৈশিষ্ট্য",
    testimonialsTitle: "মানুষ কী বলে",
    cardTemplates: "কার্ড টেমপ্লেট",
    templateMothersDay: "শুভ মাতৃ দিবস",
    templateILoveYou: "আমি তোমাকে ভালোবাসি",
    templateHero: "তুমিই আমার হিরো",
    fontChoice: "ফন্ট স্টাইল",
    colorTheme: "রঙের থিম",
    preset: "প্রিসেট",
    custom: "কাস্টম",
    collageTitle: "ফটো কোলাজ তৈরি",
    collageDesc: "মায়ের জন্য সুন্দর ফটো কোলাজ তৈরি করুন",
    chooseLayout: "লেআউট বেছে নিন",
    addPhotos: "ছবি যোগ করুন",
    collageTitleLabel: "কোলাজ শিরোনাম",
    downloadCollage: "কোলাজ ডাউনলোড",
    shareCollage: "কোলাজ শেয়ার",
    layoutGrid: "গ্রিড",
    layoutHeart: "হার্ট",
    layoutCircle: "বৃত্ত",
    layoutStrip: "ফটো স্ট্রিপ",
    couponTitle: "মায়ের কুপন",
    couponDesc: "মায়ের জন্য প্রেম কুপন তৈরি করুন",
    addCoupon: "কুপন যোগ করুন",
    redeem: "ব্যবহার করুন",
    redeemed: "ব্যবহৃত",
    printCoupons: "কুপন বই প্রিন্ট",
    customCoupon: "কাস্টম কুপন",
    bucketListTitle: "মা ও আমার বাকেট লিস্ট",
    bucketListDesc: "সময় শেষ হওয়ার আগে একসাথে করার জিনিস",
    addItem: "আইটেম যোগ করুন",
    completed: "সম্পন্ন",
    remaining: "বাকি",
    adventures: "অ্যাডভেঞ্চার",
    food: "খাবার",
    qualityTime: "মানসম্মত সময়",
    learning: "শিক্ষা",
    giftBoxTitle: "ডিজিটাল গিফট বক্স",
    giftBoxDesc: "মায়ের জন্য একটি সারপ্রাইজ গিফট বক্স তৈরি করুন",
    openGift: "গিফট বক্স খুলুন",
    addGift: "উপহার যোগ করুন",
    textGift: "ভালোবাসার বার্তা",
    photoGift: "ফটো উপহার",
    couponGift: "কুপন উপহার",
    chooseTheme: "বক্সের থিম বেছে নিন",
    jarTitle: "মেমোরি জার",
    jarDesc: "ভালোবাসার নোট ও স্মৃতি দিয়ে একটি জার পূরণ করুন",
    addNote: "নোট যোগ করুন",
    drawNote: "একটি নোট টানুন",
    shakeJar: "জার ঝাঁকান",
    noteText: "আপনার ভালোবাসার কথা...",
    boothTitle: "ফটো বুথ",
    boothDesc: "মায়ের সাথে মজার ছবি তুলুন",
    startCamera: "ক্যামেরা শুরু",
    capture: "ক্যাপচার!",
    filterNone: "সাধারণ",
    filterWarm: "উষ্ণ",
    filterVintage: "ভিনটেজ",
    filterBW: "সাদা-কালো",
    filterVibrant: "ভাইব্র্যান্ট",
    frameBestMom: "সেরা মা",
    frameHearts: "হার্ট",
    frameFlowers: "ফুল",
    saveToGallery: "গ্যালারিতে সংরক্ষণ",
    downloadPhoto: "ডাউনলোড",
    shareTitle: "মায়ের সাথে শেয়ার",
    share: "শেয়ার",
    shareWhatsApp: "হোয়াটসঅ্যাপ",
    shareFacebook: "ফেসবুক",
    shareTwitter: "টুইটার/X",
    shareCopyLink: "লিংক কপি",
    shareDownload: "ছবি ডাউনলোড",
    shareText: "আমি এটি আমার মায়ের জন্য তৈরি করেছি! ❤️ #LoveYouMom #BuiltWithTRAE",
    builtWithTRAE: "TRAE IDE দিয়ে তৈরি",
  },
};

type Lang = "en" | "bn";
const LanguageContext = createContext<{ lang: Lang; t: (key: string) => string; toggle: () => void }>({
  lang: "en",
  t: (k) => translations.en[k] || k,
  toggle: () => {},
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");
  const toggle = () => setLang((l) => (l === "en" ? "bn" : "en"));
  const t = (key: string) => translations[lang][key] || translations.en[key] || key;
  return <LanguageContext.Provider value={{ lang, t, toggle }}>{children}</LanguageContext.Provider>;
}

export const useLang = () => useContext(LanguageContext);
